version: '3'
services:
  minio:
    image: bitnami/minio:latest
    restart: always
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./minio:/data
    ports:
      - 9000:9000
      - 9001:9001

  minio-create-bucket:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./src-data:/src-data
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 admin password;
      /usr/bin/mc mb myminio/datalake;
      /usr/bin/mc cp --recursive src-data myminio/datalake;
      exit 0; "

  server:
    depends_on:
      - minio
      - minio-create-bucket
    build: server/
    command: python ./server.py
    ports:
      - 8080:8080